language: node_js

node_js:
  - 12.13.1

branches:
  only:
    - "/^v?\\d{1}\\.\\d{1,2}.\\d{1,2}$/"

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - yarn install

# You can add a script with a echo to your .travis.yml file.
# This will force Travis to run your script message instead of running tests automatically.

script:
  - echo "skipping tests"

before_deploy: npm run build:pkg

deploy:
  edge: true
  provider: npm
  email: luxuemin2108@gmail.com
  # cleanup: true
  api_key:
    secure: v6sdx43zB6v2WsjGIhWVK6uAyAdnMP+qMq9576ZFKCpUzLKGG+FTnpYp+vDDjV5mz1j17MjfUe/yVfUijrQBtQyZ3j2+6QamVCAD9Nb4vvJ4ET39YqGiXsxMNixoVma2wHvShiVTG6YxM8vwuqmHCJWUMi2SinoEmvTBBlf6YLNT1yE9fPPgqxH0cxIbItOPYYDH3vHRXVRwCzmRYHG4Dc9XskUuyOn3W8Td2PmFosvUEmJLx+QjC2YAtUbZHXZ1BCbaHdda/er90eXZ/LSFTJsnG6yH6Ho4Ajs4DP/hzVeZI3hpLBcPDCvneYrbkKf3WCXlt3ZJ3ISR2rkvTZf6nw61wPSWQ98MD3Qj4rEcLm0DUWKBgU9eJw/RepZlp5Umq05FHcZVcq5/Q9pQjpyCFyigTMw9zBOpdIcQUd/ZcYhr8K97/yw7SxUUWn33WJe9nXktujM6tMDVCPP+kNOFhY4VDiPAqcNWtLi9GaZFFfv8ag7dwePNp45HbDltG1TJBVKU3E2NCDjAjoZMStj6HKiXCP4EQ23yjClNCBdhEnYqeEsIiw7QOSo5Dy8Zic7hTboEKqeCClnObPXHWz7Xq+3R1iMzQw4zgymaCoU3FTLc7ky67sowD79PCmYXfYa6c3ixmrcDI8kpLgATR44J1Mq5JeiaP9H+qOi5vvWuC4o=
  on:
    tags: true
    all_branches: true

notifications:
  email:
    recipients:
      - luxuemin2108@gmail.com
    on_success: never
    on_failure: always
